<?php

/**
 * Implements hook_menu().
 */

function views_civicrm_expose_tables_menu() { 
  $items = array(); 
    $items['admin/structure/views/expose_civicrm_tables'] = array( 
     'title' => 'Views CiviCRM Expose Tables', 
     'description' => 'Configuration for the Views CiviCRM Expose Table module.', 
     'page callback' => 'drupal_get_form', 
     'page arguments' => array('views_civicrm_expose_tables_admin_form'), 
     'access arguments' => array('administer site configuration'),
     'type' => MENU_NORMAL_ITEM, 
	  );
  return $items;
}

/** 
 *  Page Argument function for Views Expose Table admin config page
 *
 */

function views_civicrm_expose_tables_admin_form($form, &$form_state) {
  global $databases;

  $prefix_tables = $databases['default']['default']['prefix'];


  $prefix_options = array();
  $count = 0;
  foreach ($prefix_tables as $table => $db) {
    if($table != 'default'){
      $prefix_options[$table] = $table;
    }
    if($count == 1) $civi_db = $db;
  
    $count += 1;
  }
  $strip_chars = array("`",".");
  $civi_db = str_replace($strip_chars,"",$civi_db);

  $intro_text = '<p>Follow the instructions in the <a href="http://wiki.civicrm.org/confluence/display/CRMDOC/Views3+Integration" target="_blank">CiviCRM Views 3 Intregration wiki</a> first. This makes Drupal aware of the database tables. </p>'; 
  $intro_text .= '<p>Then go to the <a href="/civicrm/admin/setting/uf?reset=1 ">CiviCRM CMS Integration Settings page</a> and copy the code displayed there to your Drupal settings.php file';

  $empty = array();
  $form['views_civicrm_expose_tables_info'] = array(
    '#type' => 'markup',
    '#markup' => $intro_text,
  );

  $form['views_civicrm_expose_tables_civicrm_database'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get('views_civicrm_expose_tables_civicrm_database', $civi_db),
    '#title' => t('CiviCRM database'),
    '#description' => 'Enter the CiviCRM database name."',
  ); 
   

  $form['views_civicrm_expose_tables_prefix_tables'] = array(
    '#type' => 'checkboxes',
    '#options' => $prefix_options,
    '#title' => t('CiviCRM tables to expose as raw data to views'), 
    '#description' => t('Check the tables to expose to views as base tables'), 
    '#default_value' => variable_get('views_civicrm_expose_tables_prefix_tables',$empty),
  );

  $form['#submit'][] = 'views_civicrm_expose_tables_admin_form_submit';

  return system_settings_form($form);
}

/** 
 * Form submit handler for Views Expose Table admin config page
 *
 */

function views_civicrm_expose_tables_admin_form_submit($form, &$form_state) { 
  variable_set('views_civicrm_expose_tables_prefix_tables', $form_state['values']['views_civicrm_expose_tables_prefix_tables']); 
  variable_set('views_civicrm_expose_tables_civicrm_database', $form_state['values']['views_civicrm_expose_tables_civicrm_database']); 
  //clear views cache, not views data cache
  cache_clear_all('*', 'cache_views', TRUE);
}

/**
 * Implements hook_views_api().
 */

function views_civicrm_expose_tables_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'views_civicrm_expose_tables') . '/includes',
  );
}

